package com.proyecto.appfacturacion.entities;

public enum Estado {
    Aguascalientes,
    Baja_California,
    Baja_California_Sur,
    Campeche,
    Chiapas,
    Chihuahua,
    Coahuila,
    Colima,
    Durango,
    Guanajuato,
    Guerrero,
    Hidalgo,
    Jalisco,
    Mexico,
    Michoacan,
    Morelos,
    Nayarit,
    Nuevo_Leon,
    Oaxaca,
    Puebla,
    Queretaro,
    Quintana_Roo,
    San_Luis_Potosi,
    Sinaloa,
    Sonora,
    Tabasco,
    Tamaulipas,
    Tlaxcala,
    Veracruz,
    Yucatan,
    Zacatecas,
    Ciudad_de_Mexico,
    Estado_de_Mexico;
}
