package com.proyecto.appfacturacion.entities;

public enum RegimenFiscal {
    GENERAL_DE_LEY_PERSONAS_MORALES,
    PERSONAS_MORALES_CON_FINES_NO_LUCRATIVOS,
    REGIMEN_DE_ENAJENACION_O_ADQUISICION_DE_BIENES,
    RESIDENTES_EN_EL_EXTRANJERO_SIN_ESTABLECIMIENTO_PERMANENTE_EN_MEXICO,
    ACTIVIDADES_AGRICOLAS_GANADERAS_SILVICOLAS_Y_PESQUERAS,
    REGIMEN_SIMPLIFICADO_DE_CONFIANZA,
    Hidrocarburos,
    SUELDOS_Y_SALARIOS,
    Arrendamiento,
    INGRESOS_POR_INTERESES,
    INCORPORACION_FISCAL

}

